@rooturl=http://localhost:9001/api/v1

##
@userEP={{rooturl}}/users

@transactionEP={{rooturl}}/transactions

###
POST {{userEP}}/register
Content-Type: application/json

{
    "username":"kiara",
    "email":"tokenchec@gmail.com",
    "password": "123"
}

###
POST {{userEP}}/login
Content-Type: application/json

{
    "email":"tokenchec@gmail.com",
    "password": "123"
}


### 
#creating transaction

POST {{transactionEP}}
Content-Type: application/json

{
    "type": "income",
    "amount":100,
    "date": "10-10-2024",
    "description": "STOCKS"
}