@rooturl=http://localhost:9001/api/v1

##
@userEP={{rooturl}}/users

@transactionEP={{rooturl}}/transactions

###
POST {{userEP}}/register
Content-Type: application/json

{
    "username":"kiara",
    "email":"test@gmail.com",
    "password": "123"
}

###
POST {{userEP}}/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password": "123"
}


### 
#creating transaction
POST {{transactionEP}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzM3NDMyNTUwLCJleHAiOjE3Mzc1MTg5NTB9.YqPmPnI3cBUimhiFKoJWXlJ2DboUz-stLJVrJ4q5t9w

{
    "type": "Income",
    "amount":100,
    "date": "10-10-2024",
    "description": "STOCKS"
}

###
#get transaction
GET {{transactionEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzM3NDMyNTUwLCJleHAiOjE3Mzc1MTg5NTB9.YqPmPnI3cBUimhiFKoJWXlJ2DboUz-stLJVrJ4q5t9w



###delete transcation 
DELETE {{transactionEP}}/678f2071ed80a9f37f56c756
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzM3NDMyNTUwLCJleHAiOjE3Mzc1MTg5NTB9.YqPmPnI3cBUimhiFKoJWXlJ2DboUz-stLJVrJ4q5t9w

### delete many 
DELETE {{transactionEP}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzM3NDMyNTUwLCJleHAiOjE3Mzc1MTg5NTB9.YqPmPnI3cBUimhiFKoJWXlJ2DboUz-stLJVrJ4q5t9w

{
    "transactions" : [
        "678f211cc23ba2398f7f440f","678f211cc23ba2398f7f4409","678f211cc23ba2398f7f440c"

    ]
}

